sonar.projectKey=vamsikrishna2049_nodejs-app
sonar.projectName=Node.js Application
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,**/*.test.js

sonar.qualitygate.wait=true
sonar.links.scm=https://github.com/vamsikrishna2049/nodejs-app
sonar.links.ci=https://github.com/vamsikrishna2049/nodejs-app/actions
